insert into model(makers_id, model) VALUES
                                        (42,'Civic'),
                                        (72,'Altima'),
                                        (92,'Corolla'),
                                        (92,'Camry'),
                                        (23,'Malibu'),
                                        (23,'Impalla'),
                                        (23,'Silverado'),
                                        (92,'Tacoma'),
                                        (42,'CR-V'),
                                        (42,'Pilot'),
                                        (92,'Traverse'),
                                        (44,'Tucson'),
                                        (36,'Escape'),
                                        (88,'Outback'),
                                        (66,'CX5'),
                                        (88,'Forester'),
                                        (52,'Grand Cherokee'),
                                        (36,'Explorer'),
                                        (52,'Wrangler'),
                                        (23,'Equinox'),
                                        (38,'Sierra'),
                                        (92,'Highlander'),
                                        (72,'Rogue'),
                                        (92,'Rav4'),
                                        (36,'F-series')